using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using LandscapeGeneration;
using Random;
using Socium.Languages;
using Socium.Psychology;
using GeneLab;
using GeneLab.Genetix;
using System.Drawing;

namespace Socium.Nations
{
    public class Race
    {
        #region Races
        public static Race[] m_cAllRaces =
        {
        //rank 1 - usual people
            new Race("white", 1, Language.European, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteF),
                new MentalityTemplate(AdvancementRate.UniformlyPrecise, AdvancementRate.Leap, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Delayed, AdvancementRate.UniformlyPrecise)),
            new Race("latini", 1, Language.Latin, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Sparse, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.Brunette, HairsColor.DarkBlond, HairsColor.Black })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.Brunette, HairsColor.DarkBlond, HairsColor.Black })),
                new MentalityTemplate(AdvancementRate.Plateau, AdvancementRate.Delayed, AdvancementRate.Plateau, AdvancementRate.UniformlyPrecise, AdvancementRate.Delayed, AdvancementRate.UniformlyPrecise)),
            new Race("slavic", 1, Language.Slavic, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Forest}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.DarkBlond, HairsColor.Red })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.DarkBlond, HairsColor.Red })),
                new MentalityTemplate(AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Rapid, AdvancementRate.UniformlyModerate, AdvancementRate.UniformlyPrecise)),
            new Race("hindu", 1, Language.Hindu, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Delayed, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Plateau)),
            new Race("yellow", 1, Language.Asian, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanYellow,
                                                BrainGenetix.HumanSF,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Sparse, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanYellow,
                                                BrainGenetix.HumanSF,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.UniformlyPrecise, AdvancementRate.Leap, AdvancementRate.UniformlyLoose, AdvancementRate.Plateau, AdvancementRate.Plateau)),
            new Race("red", 1, Language.Aztec, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanRed,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanRed,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise)),
            new Race("hellene", 1, Language.Greek, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains/*, LandTypes<LandTypeInfoX>.Savanna*/}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond, HairsColor.Blonde })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond, HairsColor.Blonde })),
                new MentalityTemplate(AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Plateau)),
            new Race("dervish", 1, Language.Arabian, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert/*, LandTypes<LandTypeInfoX>.Savanna*/}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Plateau)),
            new Race("barb", 1, Language.Northman, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Taiga}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Savanna},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.Albino, HairsColor.DarkBlond, HairsColor.Red })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Blonde, HairsColor.Albino, HairsColor.DarkBlond, HairsColor.Red })),
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("nomad", 1, Language.Eskimoid, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanYellow,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Sparse, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanYellow,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.UniformlyPrecise, AdvancementRate.UniformlyPrecise, AdvancementRate.Delayed, AdvancementRate.Plateau, AdvancementRate.Delayed)),
            new Race("black", 1, Language.African, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle/*, LandTypes<LandTypeInfoX>.Desert*/, LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanBlack,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanBlackM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanBlack,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanBlackF),
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Plateau)),
        //rank 10 - common non-humans
            new Race("orc", 10, Language.Orkish, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, /*LandTypes<LandTypeInfoX>.Mountains, */LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Orc,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Orc,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Orc,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Orc,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.UniformlyLoose, AdvancementRate.Random, AdvancementRate.Plateau, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("goblin", 10, Language.Orkish, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, /*LandTypes<LandTypeInfoX>.Mountains, */LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Goblin,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Orc,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Goblin,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Orc,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new MentalityTemplate(AdvancementRate.Delayed)),
            new Race("centaur", 10, Language.Greek, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Forest},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Horse,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Short,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Horse,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Short,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Leap)),
            new Race("ogre", 10, Language.Orkish, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Savanna, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Forest}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Giant,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Giant,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                new MentalityTemplate(AdvancementRate.Plateau, AdvancementRate.Rapid, AdvancementRate.Random, AdvancementRate.Rapid, AdvancementRate.Plateau, AdvancementRate.Delayed)),
            new Race("halfling", 10, Language.European, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Mountains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Hobbit,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Hobbit,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteF),
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("minotaur", 10, Language.Greek, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Bull,
                                                HeadGenetix.Human,
                                                LegsGenetix.Demon,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.Barbarian,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Herbivore,
                                                EyesGenetix.Herbivore,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond, HairsColor.Red })),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("elf", 10, Language.Elven, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Elf,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Elf),
                null,
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid)),
            new Race("dwarf", 10, Language.Dwarwen, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Dwarf,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.DwarfM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Dwarf,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.DwarfF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteF),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Plateau)),
            new Race("vampire", 10, Language.European, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Vampire,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Vampire,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteF),
                new MentalityTemplate(AdvancementRate.Plateau, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Plateau, AdvancementRate.Delayed, AdvancementRate.Rapid)),
        //rank 20 - not so common non-humans
            new Race("cobold", 20, Language.Dwarwen, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Dwarf,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteM),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Dwarf,
                                                HeadGenetix.Pitecantrop,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.HumanWhiteF),
                new MentalityTemplate(AdvancementRate.UniformlyLoose, AdvancementRate.Delayed, AdvancementRate.Random, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("gnoll", 20, Language.Orkish, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Savanna, LandTypes<LandTypeInfoX>.Swamp}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Goblin,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Goblin,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Delayed)),
            new Race("satyr", 20, Language.Greek, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Demon,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Demon,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.Rapid, AdvancementRate.Leap, AdvancementRate.Delayed, AdvancementRate.UniformlyLoose, AdvancementRate.Rapid)),
            new Race("werewolf", 20, Language.European, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Werevolf,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcM,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Werevolf,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.OrcF,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Leap, AdvancementRate.Leap, AdvancementRate.Rapid, AdvancementRate.Leap, AdvancementRate.Plateau)),
            new Race("feline", 20, Language.African, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Savanna, LandTypes<LandTypeInfoX>.Forest}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Furry,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Cat,
                                                HairsGenetix.AnimalWhiskers),
                null,
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Leap, AdvancementRate.Delayed, AdvancementRate.Rapid)),
            //new RaceTemplate("yeti", 20, Language.Eskimoid, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Tundra}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle}),
            //new RaceTemplate("littlefolk ", 20, Language.Elven, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Plains}),
            new Race("lizard", 20, Language.Aztec, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Mountains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Furry,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Reptile,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Animal,
                                                EarsGenetix.None,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Delayed)),
            new Race("reptile", 20, Language.Aztec, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Reptile,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Animal,
                                                EarsGenetix.None,
                                                EyesGenetix.Fish,
                                                HairsGenetix.None),
                null,
                new MentalityTemplate(AdvancementRate.UniformlyLoose, AdvancementRate.Rapid, AdvancementRate.UniformlyLoose, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Plateau)),
            //new RaceTemplate("half-elf ", 20, Language.Elven, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Forest}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Savanna}),
            //new RaceTemplate("half-orc ", 20, Language.Orkish, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Forest}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra}),
        //rank 30 - exotic non-humans
            new Race("ratling", 30, Language.Asian, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Goblin,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Beast,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Barbarian,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                null,
                new MentalityTemplate(AdvancementRate.Plateau, AdvancementRate.Delayed, AdvancementRate.Plateau, AdvancementRate.Delayed, AdvancementRate.Plateau, AdvancementRate.Plateau)),
            new Race("ursan", 30, Language.Slavic, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Furry,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.Short,
                                                HideGenetix.Beast,
                                                BrainGenetix.HumanReal,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Animal,
                                                EarsGenetix.Carnivore,
                                                EyesGenetix.Human,
                                                HairsGenetix.AnimalWhiskers),
                null,
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Plateau, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Plateau, AdvancementRate.Delayed)),
            //new RaceTemplate("half-dragon ", 30, Language.Drow, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Desert}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Taiga}),
            //new RaceTemplate("half-dwarf ", 30, NameGenerator.Language.Dwarf, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Plains}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp}),
            //new RaceTemplate("half-faery ", 30, NameGenerator.Language.Elf1, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Plains}, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Swamp}),
            //new RaceTemplate("golem ", 30, NameGenerator.Language.Aztec, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Savanna, }, 
            //    new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains}),
            new Race("naga", 30, Language.Hindu, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Savanna, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Snake,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.None,
                                                TailGenetix.Long,
                                                HideGenetix.Reptile,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                null,
                new MentalityTemplate(AdvancementRate.Leap, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid)),
            new Race("harpy", 30, Language.Greek, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Swamp},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Bird,
                                                ArmsGenetix.Human,
                                                WingsGenetix.Bird,
                                                TailGenetix.Short,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.HarpyM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Bird,
                                                ArmsGenetix.Human,
                                                WingsGenetix.Bird,
                                                TailGenetix.Short,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Barbarian,
                                                LifeCycleGenetix.HarpyF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("faery", 30, Language.Elven, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Mountains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Pixie,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.Insect,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.HarpyM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Elf),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Pixie,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.Insect,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.HarpyF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Elf),
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Random, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid)),
            new Race("pixie", 30, Language.Elven, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Mountains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Pixie,
                                                HeadGenetix.Human,
                                                LegsGenetix.Snake,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.Insect,
                                                TailGenetix.Long,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.HarpyM,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Elf),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Pixie,
                                                HeadGenetix.Human,
                                                LegsGenetix.Snake,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.Insect,
                                                TailGenetix.Long,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.HarpyF,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Elf),
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Random, AdvancementRate.Random, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Rapid)),
            new Race("drow", 30, Language.Drow, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Drow,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                HairsGenetix.Drow),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid)),
        //rank 40 - powerful mythic creatures
            new Race("djinn", 40, Language.Arabian, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Plains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Ifrit,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Ifrit,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.UniformlyLoose)),
            new Race("rakshasa", 40, Language.Hindu, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Navi,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Human,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Delayed)),
            new Race("asura", 40, Language.Hindu, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Savanna}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Giant,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.Thick, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Giant,
                                                HeadGenetix.Human,
                                                LegsGenetix.Human,
                                                ArmsGenetix.Human4,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanTan,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Human,
                                                FaceGenetix.Human,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Human,
                                                new HairsGenetix(HairsAmount.Thick, HairsAmount.None, HairsType.Hair, new HairsColor[] { HairsColor.Brunette, HairsColor.Black, HairsColor.DarkBlond })),
                new MentalityTemplate(AdvancementRate.Plateau, AdvancementRate.Rapid, AdvancementRate.Plateau, AdvancementRate.Rapid, AdvancementRate.Delayed, AdvancementRate.Plateau)),
            new Race("drakonid", 40, Language.Drow, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Taiga},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Human,
                                                LegsGenetix.Bird,
                                                ArmsGenetix.Human,
                                                WingsGenetix.Bat,
                                                TailGenetix.Long,
                                                HideGenetix.Reptile,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.Barbarian,
                                                FaceGenetix.Animal,
                                                EarsGenetix.None,
                                                EyesGenetix.Human,
                                                HairsGenetix.None),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.UniformlyLoose, AdvancementRate.UniformlyLoose, AdvancementRate.Delayed)),
        //rank 50 - complete aliens
            new Race("insectoid", 50, Language.African, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Savanna, LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Desert}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Plains},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Elf,
                                                HeadGenetix.Insect,
                                                LegsGenetix.Insect6,
                                                ArmsGenetix.Insect4,
                                                WingsGenetix.Insect,
                                                TailGenetix.Long,
                                                HideGenetix.Insect,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.InsectM,
                                                FaceGenetix.Insect,
                                                EarsGenetix.None,
                                                EyesGenetix.Insect,
                                                HairsGenetix.None),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Elf,
                                                HeadGenetix.Insect,
                                                LegsGenetix.Insect6,
                                                ArmsGenetix.Insect4,
                                                WingsGenetix.Insect,
                                                TailGenetix.Long,
                                                HideGenetix.Insect,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.InsectF,
                                                FaceGenetix.Insect,
                                                EarsGenetix.None,
                                                EyesGenetix.Insect,
                                                HairsGenetix.None),
                new MentalityTemplate(AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Rapid)),
            new Race("arachnid", 50, Language.Drow, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Swamp, LandTypes<LandTypeInfoX>.Jungle}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Desert, LandTypes<LandTypeInfoX>.Tundra},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Insect,
                                                LegsGenetix.Insect8,
                                                ArmsGenetix.Insect2,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Insect,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.InsectM,
                                                FaceGenetix.Insect,
                                                EarsGenetix.None,
                                                EyesGenetix.Spider,
                                                HairsGenetix.None),
                new Phenotype<LandTypeInfoX>(BodyGenetix.Barbarian,
                                                HeadGenetix.Insect,
                                                LegsGenetix.Insect8,
                                                ArmsGenetix.Insect2,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.Insect,
                                                BrainGenetix.HumanFantasy,
                                                LifeCycleGenetix.InsectF,
                                                FaceGenetix.Insect,
                                                EarsGenetix.None,
                                                EyesGenetix.Spider,
                                                HairsGenetix.None),
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed)),
            new Race("illithid", 50, Language.Aztec, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Mountains, LandTypes<LandTypeInfoX>.Jungle, LandTypes<LandTypeInfoX>.Desert}, 
                //new LandTypeInfoX[] {LandTypes<LandTypeInfoX>.Taiga, LandTypes<LandTypeInfoX>.Tundra, LandTypes<LandTypeInfoX>.Forest, LandTypes<LandTypeInfoX>.Plains, LandTypes<LandTypeInfoX>.Savanna},
                new Phenotype<LandTypeInfoX>(BodyGenetix.Human,
                                                HeadGenetix.Human,
                                                LegsGenetix.Ktulhu,
                                                ArmsGenetix.Human,
                                                WingsGenetix.None,
                                                TailGenetix.None,
                                                HideGenetix.HumanWhite,
                                                BrainGenetix.Elf,
                                                LifeCycleGenetix.Elf,
                                                FaceGenetix.Ktulhu,
                                                EarsGenetix.Elf,
                                                EyesGenetix.Ktulhu,
                                                HairsGenetix.Ktulhu),
                null,
                new MentalityTemplate(AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Delayed, AdvancementRate.Rapid, AdvancementRate.Rapid, AdvancementRate.Delayed)),
        };
        #endregion

        public string m_sName;
        public int m_iRank;
        public Language m_pLanguage;

        public Phenotype<LandTypeInfoX> m_pPhenotypeM;

        public Phenotype<LandTypeInfoX> m_pPhenotypeF;

        public List<Nation> m_cNations = new List<Nation>();

        public MentalityTemplate m_pMentalityTemplate;

        public Race(string sName, int iRank, Language pLanguage, Phenotype<LandTypeInfoX> pFenotypeM, Phenotype<LandTypeInfoX> pFenotypeF, MentalityTemplate pCulture)
        { 
            m_sName = sName;
            m_iRank = iRank;

            m_pLanguage = pLanguage;

            m_pPhenotypeM = (Phenotype<LandTypeInfoX>)pFenotypeM.MutateRace();
            if (m_pPhenotypeM.ValueOf<HairsGenetix>().m_cHairColors.Count == 0 &&
                (m_pPhenotypeM.ValueOf<HairsGenetix>().m_eHairs != HairsAmount.None ||
                 m_pPhenotypeM.ValueOf<HairsGenetix>().m_eBeard != HairsAmount.None))
                throw new Exception();

            if (pFenotypeF == null)
                pFenotypeF = pFenotypeM;

            m_pFenotypeF = (Phenotype<LandTypeInfoX>)pFenotypeF.MutateRace();
            if (m_pFenotypeF.ValueOf<HairsGenetix>().m_cHairColors.Count == 0 &&
                (m_pFenotypeF.ValueOf<HairsGenetix>().m_eHairs != HairsAmount.None ||
                 m_pFenotypeF.ValueOf<HairsGenetix>().m_eBeard != HairsAmount.None))
                throw new Exception();

            m_pMentalityTemplate = pCulture;
        }

        public override string ToString()
        {
            return m_sName.Trim();
        }

        public void ResetNations()
        {
            m_cNations.Clear();
        }
    }
}
