//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by QuickFilter.rc
//
#define IDS_PROJNAME                    100
#define IDB_QFILTER                     101
#define IDR_QFILTER                     102
#define IDD_QFILTER                     103
#define IDR_CHECKFILTER                 104
#define IDS_PLATFORM_WIN32_NT           110
#define IDS_PLATFORM_WIN32_NTAS         111
#define IDD_ABOUTDLG                    112
#define IDS_PLATFORM_WIN32_NTW          112
#define IDS_PLATFORM_WIN32_NTS          113
#define IDS_PLATFORM_WIN32s             114
#define IDD_QFILTER_PROP_PAGE_GENERAL   114
#define IDS_PLATFORM_WIN32_WINDOWS95    115
#define IDS_PLATFORM_UNKNOWN            116
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUMPRO 117
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUMII 118
#define IDS_PLATFORM_WIN32_WINDOWS98    119
#define IDS_PROCESSOR_ARCHITECTURE_UNKNOWN 120
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_386_486 121
#define IDS_PROCESSOR_ARCHITECTURE_INTEL_PENTIUM 122
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA 123
#define IDS_PROCESSOR_ARCHITECTURE_MIPS 124
#define IDS_PROCESSOR_ARCHITECTURE_PPC  125
#define IDS_PROCESSOR_LEVEL_INTEL_UNKNOWN 126
#define IDS_PROCESSOR_LEVEL_ALPHA_UNKNOWN 127
#define IDS_PROCESSOR_LEVEL_MIPS_UNKNOWN 128
#define IDB_TREE_ICONS                  129
#define IDS_PROCESSOR_LEVEL_PPC_UNKNOWN 129
#define IDS_PROCESSOR_NOREV_INTEL_386   130
#define IDS_PROCESSOR_NOREV_INTEL_486   131
#define IDS_PROCESSOR_NOREV_INTEL_PENTIUM 132
#define IDS_PROCESSOR_NOREV_MIPS_R4000  133
#define IDS_PROCESSOR_NOREV_ALPHA_21064 134
#define IDS_PROCESSOR_ARCHITECTURE_SHX  135
#define IDS_PROCESSOR_ARCHITECTURE_ARM  136
#define IDS_PROCESSOR_ARCHITECTURE_IA64 137
#define IDS_PROCESSOR_ARCHITECTURE_ALPHA64 138
#define IDS_PP_GENERAL_TITLE            145
#define IDS_PP_GENERAL_IDS_HELPFILE     146
#define IDS_PP_GENERAL_IDS_DOCSTRING    147
#define IDR_QFILTER_PROP_PAGE_GENERAL   201
#define IDI_ICON_QF                     203
#define IDB_BITMAP_NOOFCOLUMNS          210
#define IDC_EDIT_NOOFCHECKFILTERS       217
#define IDC_TAB_NOOFCOLUMNS             225
#define IDC_CHECK_LABEL                 500
#define IDC_CHECK_FILTER                700
#define IDC_ABOUT_OSVERSION             1004
#define IDC_ABOUT_PROCESSORVERSION      1006
#define IDC_ABOUT_FILEDESCRIPTION       1008
#define IDC_ABOUT_VERSION               1009
#define IDC_ABOUT_LEGALCOPYRIGHT        1010
#define IDC_ABOUT_LEGALTRADEMARKS       1011
#define IDC_ABOUT_COMMENTS              1012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
